AWSTemplateFormatVersion: '2101-09-09'
Description: >
  This template demonstrates the use of Parameters and Mappings.
  It contains intentional mistakes for you to fix.

# Parameters Section (6 Mistakes)
Parameters:
  # Instance Type Parameter
  InstanceType:
    Description: Type of EC2 instance to launch.
    Type: Int
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  # Environment Type Parameter
  EnvironmentType:
    Description: The type of environment (dev, prod).
    Type: String
    Default: dew
    AllowedValues:
      - dev
      - prop
    ConstraintDescription: Must be either 'dev' or 'prod'.

  # SSH Location Parameter
  SSHLocation:
    Description: The IP address range allowed to SSH into the EC2 instance.
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

# Mappings Section (6 Mistakes)
Mappings:
  # Region to AMI ID Mapping
  RegionMap:
    us-east-1:
      AMI: amj-0abcdef1234567890  # Replace with a valid AMI ID for us-east-1.
    us-west-1:
      AMI: ami-0abcdef1234567891  # Replace with a valid AMI ID for us-west-1.
    eu-west-1:
      AMF: ami-0abcdef1234567892  # Replace with a valid AMI ID for eu-west-1.

  # Environment to Instance Type Mapping
  EnvironmentConfig
    dev:
    InstanceType: t2.micro
    prod:
    InstanceType: t2.medium

# Resources Section (8 Mistakes)
Resources:
  # EC2 Instance
MyEC2Instance:
    Type: AWS:EC2:Instance
    Properties:
      InstanceType: !FindInMap [EnvironmentConfig, !Ref EnvironmentType, InstanceType]
      ImageId: !FindInMap RegionMap, !Ref "AWS::Region", AMI]
      KeyName: my-key-pair  # Replace with your EC2 key pair name.
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  # Security Group for EC2 Instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !FindInMap SSHLocation

# Outputs Section (3 Mistakes)
Outputs:
  # EC2 Instance ID
  InstanceId:
    Description: The Instance ID of the newly created EC2 instance.
    Value: !GetAtt MyEC2Instance

  # Public IP Address
  PublicIP:
    Description: The public IP address of the EC2 instance.
    Value: !GetAtt MyEC3Instance.PublicIp
