AWSTemplateFormatVersion: '2010-09-09'
Description: "Child stack to create an S3 bucket."

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-bucket-${AWS::StackName}-${AWS::Region}"
      AccessControl: Private

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
